"""owners and mood_events

Revision ID: 1af0bd74aec3
Revises: 
Create Date: 2026-05-29 01:21:06.407255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af0bd74aec3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mood_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mood_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mood_events_state'), ['state'], unique=False)

    op.create_table('owners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('voice_signature', sa.Text(), nullable=True),
    sa.Column('image_signature', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owners_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owners_name'))

    op.drop_table('owners')
    with op.batch_alter_table('mood_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mood_events_state'))
        batch_op.drop_index(batch_op.f('ix_mood_events_created_at'))

    op.drop_table('mood_events')
    # ### end Alembic commands ###
